version: '3'

services:
    web:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: public/
        volumes:
            - ./:/opt
        ports:
            - 8080:8080
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=web"
            DB_PATH: /opt/var
        user: ${HOST_UID}:${HOST_GID}

    devtools:
        image: matthiasnoback/php_workshop_tools_base
        volumes:
            - ./:/opt
            - ${COMPOSER_HOME}:/home/.composer
        environment:
            COMPOSER_HOME: /home/.composer
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
        depends_on:
            - web
        user: ${HOST_UID}:${HOST_GID}
